### ISSUE TITLE
[change require] vim-mode-plus operation class need defined by ES6.

### ISSUE THREAD

**Issue by t9md** [artarf/git-diff-staged#1]
Hi, I'm maintainer of vim-mode-plus.
I noticed this pkg includes vmp operation command.(by searching `consumeVimModePlus` on across github repos).
That why I open this issue to share upcoming vmp-core changes.

- Now vmp-core planing to migrate CoffeeScript based class to ES6 class.
- This change is not backward compatible.
- [Action require] Current CoffeeScript based class cannot inherit ES6 class, so need to rewrite in ES6(no other option, sorry) class based.

https://github.com/t9md/atom-vim-mode-plus/wiki/ExtendVimModePlusInInitFile
https://github.com/t9md/atom-vim-mode-plus/pull/895

**Comment by artarf** [comment]
Thanks for the notice and for the better than vim vim-emulation. There was also another problem (`setBufferPositionSafely()` does not exist anymore) which is fixed too.
